services:
  jobmanager:
    image: flink:1.19.0
    ports:
      - 8081:8081
    command: jobmanager
    volumes:
      - ./flink_config.yaml:/opt/flink/conf/config.yaml
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.19.0
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./flink_config.yaml:/opt/flink/conf/config.yaml
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@host.docker.internal:9093"
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: BROKER://host.docker.internal:9092

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERCONNECT=host.docker.internal:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/